# Generated by Django 6.0.3 on 2026-06-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='coa',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='python',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
